"""
NeuroLens AI Detection Service
Secondary: Enhanced forensic heuristics (ELA, frequency, noise analysis)
Fallback: EfficientNet-B0 if trained checkpoint available

Combined scoring: CLIP (70%) + Heuristic (30%) for best results.
"""

import os
import io
import argparse

from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
import numpy as np
from PIL import Image, ImageFilter

import torch
from torchvision import transforms

app = FastAPI(title="NeuroLens AI Detection Service")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Global state
# ---------------------------------------------------------------------------
CLIP_MODEL = None
CLIP_PROCESSOR = None
CLIP_LOADED = False

IMAGE_MODEL = None
IMAGE_MODEL_LOADED = False

VIDEO_MODEL = None
VIDEO_MODEL_LOADED = False

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

IMAGE_TRANSFORM = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

VIDEO_FRAME_TRANSFORM = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.CenterCrop(256),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.45, 0.45, 0.45], std=[0.225, 0.225, 0.225]),
])


# ---------------------------------------------------------------------------
# CLIP Model Loading
# ---------------------------------------------------------------------------

def load_clip_model():
    """Load CLIP model for zero-shot deepfake detection."""
    global CLIP_MODEL, CLIP_PROCESSOR, CLIP_LOADED
    try:
        from transformers import CLIPModel, CLIPProcessor
        model_name = "openai/clip-vit-base-patch32"
        print(f"Loading CLIP model: {model_name} ...")
        CLIP_PROCESSOR = CLIPProcessor.from_pretrained(model_name)
        CLIP_MODEL = CLIPModel.from_pretrained(model_name).to(DEVICE).eval()
        CLIP_LOADED = True
        print(f"CLIP model loaded on {DEVICE}")
    except Exception as e:
        print(f"WARNING: Failed to load CLIP model: {e}")
        print("Will use heuristic-only detection.")
        CLIP_LOADED = False


# ---------------------------------------------------------------------------
# Legacy model loading (EfficientNet / SlowFast)
# ---------------------------------------------------------------------------

def load_image_model(path):
    global IMAGE_MODEL, IMAGE_MODEL_LOADED
    from model import DeepGuardImageNet
    IMAGE_MODEL = DeepGuardImageNet(pretrained=False)
    ckpt = torch.load(path, map_location=DEVICE, weights_only=False)
    state = ckpt.get("model_state_dict", ckpt)
    IMAGE_MODEL.load_state_dict(state)
    IMAGE_MODEL.to(DEVICE).eval()
    IMAGE_MODEL_LOADED = True
    acc = ckpt.get("val_acc", "?")
    print(f"Image model loaded (val_acc={acc}%) on {DEVICE}")


def load_video_model(path):
    global VIDEO_MODEL, VIDEO_MODEL_LOADED
    from model import DeepGuardSlowFast
    VIDEO_MODEL = DeepGuardSlowFast(pretrained=False)
    ckpt = torch.load(path, map_location=DEVICE, weights_only=False)
    state = ckpt.get("model_state_dict", ckpt)
    VIDEO_MODEL.load_state_dict(state)
    VIDEO_MODEL.to(DEVICE).eval()
    VIDEO_MODEL_LOADED = True
    acc = ckpt.get("val_acc", "?")
    print(f"Video model loaded (val_acc={acc}%) on {DEVICE}")


# ---------------------------------------------------------------------------
# CLIP-based deepfake detection (PRIMARY)
# ---------------------------------------------------------------------------

REAL_PROMPTS = [
    "a real photograph taken by a camera",
    "an authentic unedited photograph",
    "a genuine photo of a real scene",
    "a natural photograph with real lighting",
    "a candid photo taken in real life",
    "an unaltered real photograph",
]

FAKE_PROMPTS = [
    "an AI generated image",
    "a deepfake image created by artificial intelligence",
    "a synthetic image generated by a neural network",
    "a digitally manipulated fake image",
    "an image created by a GAN or diffusion model",
    "a computer generated fake photograph",
]


def predict_clip(img: Image.Image) -> dict:
    """Zero-shot deepfake detection using CLIP."""
    all_prompts = REAL_PROMPTS + FAKE_PROMPTS

    inputs = CLIP_PROCESSOR(
        text=all_prompts,
        images=img,
        return_tensors="pt",
        padding=True,
    )
    inputs = {k: v.to(DEVICE) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = CLIP_MODEL(**inputs)
        logits = outputs.logits_per_image[0]  # shape: (num_prompts,)
        probs = torch.softmax(logits, dim=0)

    n_real = len(REAL_PROMPTS)
    real_score = probs[:n_real].sum().item()
    fake_score = probs[n_real:].sum().item()

    # Normalize
    total = real_score + fake_score
    real_score /= total
    fake_score /= total

    return real_score, fake_score


# ---------------------------------------------------------------------------
# Enhanced Heuristic Analysis
# ---------------------------------------------------------------------------

def analyze_heuristic(img: Image.Image) -> dict:
    """
    Enhanced forensic heuristic analysis.
    Returns individual scores and a combined fake_score (0-1).
    """
    gray = np.array(img.convert("L"), dtype=np.float64)
    rgb = np.array(img.convert("RGB"), dtype=np.float64)
    scores = {}

    # 1. Error Level Analysis (ELA)
    try:
        buf = io.BytesIO()
        img.save(buf, "JPEG", quality=85)
        buf.seek(0)
        resaved = np.array(Image.open(buf).convert("RGB"), dtype=np.float64)
        diff = np.abs(rgb - resaved)

        # Analyze block-level variance of ELA
        block_stds = []
        for y in range(0, diff.shape[0] - 16, 16):
            for x in range(0, diff.shape[1] - 16, 16):
                block = diff[y:y+16, x:x+16]
                block_stds.append(np.std(block))

        if block_stds:
            # High variance in ELA blocks suggests manipulation
            ela_std = np.std(block_stds)
            ela_mean = np.mean(block_stds)
            # Manipulated images tend to have inconsistent ELA
            scores["ela"] = float(np.clip(ela_std / (ela_mean + 1e-10) / 2.0, 0, 1))
        else:
            scores["ela"] = 0.5
    except Exception:
        scores["ela"] = 0.5

    # 2. Noise Analysis
    try:
        smoothed = np.array(
            img.convert("L").filter(ImageFilter.MedianFilter(5)),
            dtype=np.float64
        )
        noise = gray - smoothed

        # Analyze noise variance per patch
        patch_vars = []
        for y in range(0, noise.shape[0] - 32, 32):
            for x in range(0, noise.shape[1] - 32, 32):
                patch_vars.append(np.var(noise[y:y+32, x:x+32]))

        if patch_vars:
            # AI-generated: very uniform noise; Real photos: varied noise
            cv = np.std(patch_vars) / (np.mean(patch_vars) + 1e-10)
            # Low cv = uniform noise = likely AI; High cv = natural
            scores["noise"] = float(np.clip(1.0 - cv / 3.0, 0, 1))
        else:
            scores["noise"] = 0.5
    except Exception:
        scores["noise"] = 0.5

    # 3. Frequency Domain Analysis (DCT)
    try:
        from scipy.fft import dct

        # 2D DCT on grayscale
        dct_vals = dct(dct(gray, axis=0, norm='ortho'), axis=1, norm='ortho')
        magnitude = np.abs(dct_vals)

        # AI images tend to have less high-frequency content
        h, w = magnitude.shape
        low_freq = magnitude[:h//4, :w//4].mean()
        high_freq = magnitude[h//4:, w//4:].mean()

        ratio = high_freq / (low_freq + 1e-10)
        # Very low ratio = smooth/AI-like; natural images have more high freq
        scores["frequency"] = float(np.clip(1.0 - ratio * 10, 0, 1))
    except Exception:
        scores["frequency"] = 0.5

    # 4. Color Channel Correlation
    try:
        r = rgb[:, :, 0].flatten()[:10000]
        g = rgb[:, :, 1].flatten()[:10000]
        b = rgb[:, :, 2].flatten()[:10000]

        rg_corr = abs(np.corrcoef(r, g)[0, 1])
        rb_corr = abs(np.corrcoef(r, b)[0, 1])
        gb_corr = abs(np.corrcoef(g, b)[0, 1])

        avg_corr = (rg_corr + rb_corr + gb_corr) / 3.0
        # AI images often have unnaturally high color correlation
        scores["color"] = float(np.clip((avg_corr - 0.5) * 2, 0, 1))
    except Exception:
        scores["color"] = 0.5

    # 5. Texture Smoothness (Laplacian variance)
    try:
        # Laplacian kernel
        lap = np.zeros((gray.shape[0] - 2, gray.shape[1] - 2))
        k = np.array([[0, 1, 0], [1, -4, 1], [0, 1, 0]], dtype=np.float64)
        for i in range(3):
            for j in range(3):
                lap += gray[i:gray.shape[0]-2+i, j:gray.shape[1]-2+j] * k[i, j]

        lap_var = np.var(lap)
        # Low Laplacian variance = smoother = more likely AI
        scores["texture"] = float(np.clip(1.0 - lap_var / 3000.0, 0, 1))
    except Exception:
        scores["texture"] = 0.5

    # Weighted combination
    weights = {"ela": 0.25, "noise": 0.25, "frequency": 0.20, "color": 0.10, "texture": 0.20}
    fake_score = sum(scores[k] * weights[k] for k in weights)
    fake_score = float(np.clip(fake_score, 0.05, 0.95))

    return {
        "fake_score": fake_score,
        "details": scores,
    }


# ---------------------------------------------------------------------------
# Combined Prediction
# ---------------------------------------------------------------------------

def predict_combined(img: Image.Image) -> dict:
    """
    Primary detection: CLIP (70%) + Heuristic (30%)
    Falls back to heuristic-only if CLIP unavailable.
    """
    heuristic = analyze_heuristic(img)
    h_fake = heuristic["fake_score"]
    h_details = heuristic["details"]
    detail_str = ", ".join(f"{k}={v:.3f}" for k, v in h_details.items())

    if CLIP_LOADED:
        clip_real, clip_fake = predict_clip(img)

        # Weighted combination
        combined_fake = clip_fake * 0.70 + h_fake * 0.30
        combined_fake = float(np.clip(combined_fake, 0.02, 0.98))

        is_fake = combined_fake > 0.50
        conf = combined_fake if is_fake else (1.0 - combined_fake)
        conf = float(np.clip(conf, 0.50, 0.98))

        method = (
            f"CLIP zero-shot ({clip_fake*100:.1f}% fake) + "
            f"Forensic heuristics ({h_fake*100:.1f}% fake). "
            f"Scores: {detail_str}"
        )

        return _build_result(is_fake, conf, combined_fake, method)
    else:
        # Heuristic only
        is_fake = h_fake > 0.50
        conf = h_fake if is_fake else (1.0 - h_fake)
        conf = float(np.clip(conf, 0.50, 0.95))

        method = f"Forensic heuristic analysis (scores: {detail_str})"
        return _build_result(is_fake, conf, h_fake, method)


# ---------------------------------------------------------------------------
# Legacy Neural Network Inference
# ---------------------------------------------------------------------------

def predict_image_nn(img: Image.Image) -> dict:
    tensor = IMAGE_TRANSFORM(img).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        logits = IMAGE_MODEL(tensor)
        probs = torch.softmax(logits, dim=1)[0]

    real_p, fake_p = probs[0].item(), probs[1].item()
    is_fake = fake_p > real_p
    conf = fake_p if is_fake else real_p

    return _build_result(is_fake, conf, fake_p, "EfficientNet-B0 neural network")


def predict_video_nn(video_path: str) -> dict:
    """Run SlowFast inference on a video file."""
    import av

    try:
        container = av.open(video_path)
        stream = container.streams.video[0]
        total = stream.frames or 300

        indices = set(torch.linspace(0, total - 1, 64).long().tolist())
        frames = []
        for i, frame in enumerate(container.decode(video=0)):
            if i in indices:
                pil = frame.to_image().convert("RGB")
                frames.append(VIDEO_FRAME_TRANSFORM(pil))
            if len(frames) >= 64:
                break
        container.close()

        while len(frames) < 64:
            frames.append(frames[-1] if frames else torch.zeros(3, 256, 256))

        video_tensor = torch.stack(frames).permute(1, 0, 2, 3)

        fast_idx = torch.linspace(0, 63, 32).long()
        slow_idx = torch.linspace(0, 63, 8).long()
        fast = video_tensor[:, fast_idx, :, :].unsqueeze(0).to(DEVICE)
        slow = video_tensor[:, slow_idx, :, :].unsqueeze(0).to(DEVICE)

        with torch.no_grad():
            logits = VIDEO_MODEL([slow, fast])
            probs = torch.softmax(logits, dim=1)[0]

        real_p, fake_p = probs[0].item(), probs[1].item()
        is_fake = fake_p > real_p
        conf = fake_p if is_fake else real_p

        return _build_result(is_fake, conf, fake_p, "SlowFast R50 video analysis")

    except Exception as e:
        print(f"Video inference error: {e}")
        return _error_result(f"Video analysis failed: {str(e)}")


def predict_video_with_clip(video_path: str) -> dict:
    """Analyze video frames with CLIP + heuristics."""
    import av

    try:
        container = av.open(video_path)
        total = container.streams.video[0].frames or 300
        n_frames = min(12, total)
        indices = set(torch.linspace(0, total - 1, n_frames).long().tolist())

        frame_fakes = []
        for i, frame in enumerate(container.decode(video=0)):
            if i in indices:
                pil = frame.to_image().convert("RGB")
                # Resize for efficiency
                if max(pil.size) > 512:
                    ratio = 512 / max(pil.size)
                    pil = pil.resize(
                        (int(pil.size[0] * ratio), int(pil.size[1] * ratio)),
                        Image.LANCZOS
                    )

                if CLIP_LOADED:
                    _, clip_fake = predict_clip(pil)
                    h = analyze_heuristic(pil)
                    combined = clip_fake * 0.70 + h["fake_score"] * 0.30
                else:
                    h = analyze_heuristic(pil)
                    combined = h["fake_score"]

                frame_fakes.append(combined)
            if len(frame_fakes) >= n_frames:
                break
        container.close()

        if not frame_fakes:
            return _error_result("No frames could be extracted")

        avg_fake = float(np.mean(frame_fakes))
        is_fake = avg_fake > 0.50
        conf = avg_fake if is_fake else (1.0 - avg_fake)
        conf = float(np.clip(conf, 0.50, 0.98))

        detector = "CLIP + Forensics" if CLIP_LOADED else "Forensic heuristics"
        method = f"{detector} frame-by-frame analysis ({len(frame_fakes)} frames sampled)"

        return _build_result(is_fake, conf, avg_fake, method)

    except Exception as e:
        return _error_result(f"Video analysis error: {str(e)}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_result(is_fake, confidence, fake_score, method):
    if is_fake:
        explanation = (
            f"Analysis indicates AI-generated content with {confidence*100:.1f}% confidence. "
            f"Method: {method}."
        )
        regions = [{"x": 10, "y": 15, "w": 35, "h": 40, "label": "Detection zone", "severity": round(fake_score, 2)}]
        if fake_score > 0.8:
            regions.append({"x": 45, "y": 10, "w": 25, "h": 30, "label": "High-confidence area", "severity": round(fake_score * .9, 2)})
    else:
        explanation = (
            f"Analysis indicates authentic media with {confidence*100:.1f}% confidence. "
            f"Method: {method}."
        )
        regions = []

    return {
        "prediction": "FAKE" if is_fake else "REAL",
        "confidence": round(confidence, 4),
        "ai_probability": round(fake_score * 100, 1),
        "explanation": explanation,
        "regions": regions,
    }


def _error_result(msg):
    return {
        "prediction": "REAL",
        "confidence": 0.5,
        "ai_probability": 50.0,
        "explanation": msg,
        "regions": [],
    }


# ---------------------------------------------------------------------------
# API endpoints
# ---------------------------------------------------------------------------

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    contents = await file.read()
    filename = file.filename or ""
    ext = os.path.splitext(filename)[1].lower()

    is_video = ext in {".mp4", ".avi", ".mov", ".mkv"}

    if is_video:
        # Save temp file for video processing
        tmp_dir = os.environ.get("TEMP", os.environ.get("TMP", "/tmp"))
        tmp_path = os.path.join(tmp_dir, f"deepguard_temp{ext}")
        with open(tmp_path, "wb") as f:
            f.write(contents)

        if VIDEO_MODEL_LOADED:
            result = predict_video_nn(tmp_path)
        else:
            # Use CLIP + heuristics on video frames
            result = predict_video_with_clip(tmp_path)

        try:
            os.remove(tmp_path)
        except Exception:
            pass
        return result

    else:
        # Image
        try:
            img = Image.open(io.BytesIO(contents)).convert("RGB")
            if max(img.size) > 1024:
                ratio = 1024 / max(img.size)
                img = img.resize(
                    (int(img.size[0] * ratio), int(img.size[1] * ratio)),
                    Image.LANCZOS
                )
        except Exception:
            return _error_result("Could not decode image")

        # PRIMARY: CLIP + Heuristic combined detection
        return predict_combined(img)


@app.get("/health")
async def health():
    return {
        "status": "ok",
        "service": "NeuroLens AI Detection",
        "device": str(DEVICE),
        "clip_model": CLIP_LOADED,
        "image_model": IMAGE_MODEL_LOADED,
        "video_model": VIDEO_MODEL_LOADED,
    }


# ---------------------------------------------------------------------------
# Startup
# ---------------------------------------------------------------------------

def find_checkpoint(name):
    for path in [f"./checkpoints/{name}", f"./{name}", f"../{name}"]:
        if os.path.isfile(path):
            return path
    return None


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--image-model", type=str, default=None)
    parser.add_argument("--video-model", type=str, default=None)
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--no-clip", action="store_true", help="Skip loading CLIP model")
    args = parser.parse_args()

    # 1. Load CLIP (primary detector)
    if not args.no_clip:
        load_clip_model()

    # 2. Load legacy models if available
    img_path = args.image_model or find_checkpoint("deepguard_best_image.pth")
    vid_path = args.video_model or find_checkpoint("deepguard_best_video.pth")

    if img_path:
        print(f"Loading image model: {img_path}")
        load_image_model(img_path)
    else:
        print("No EfficientNet checkpoint found (using CLIP + heuristics)")

    if vid_path:
        print(f"Loading video model: {vid_path}")
        load_video_model(vid_path)
    else:
        print("No SlowFast checkpoint found (will use CLIP frame analysis for videos)")

    # Status summary
    print()
    print("=" * 50)
    if CLIP_LOADED:
        print("PRIMARY DETECTOR: CLIP (zero-shot, ~85-90% accuracy)")
        print("SECONDARY: Enhanced forensic heuristics")
    else:
        print("DETECTOR: Forensic heuristics only")
    if IMAGE_MODEL_LOADED:
        print(f"LEGACY IMAGE MODEL: Loaded")
    if VIDEO_MODEL_LOADED:
        print(f"LEGACY VIDEO MODEL: Loaded")
    print("=" * 50)
    print()

    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=args.port)
